#on: [push]
#
#jobs:
#  hello_world_job:
#    runs-on: ubuntu-latest
#    name: A job to say hello
#    steps:
#      - name: Hello world action step
#        id: hello
#        uses: giuseppegargani/first_custom_action@0.0.5
#        with:
#          who-to-greet: 'Mona the Octocat'
#      # Use the output from the `hello` step
#      - name: Get the output time
#        run: echo "The time was ${{ steps.hello.outputs.time }}"
# Commento

on: [push]

jobs:
  hello_world_job:
    runs-on: macOs-latest
      permissions:
        checks: write
        contents: read
        issues: read
        pull-requests: write
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2.3.4
      # Si potrebbe usare qualsiasi Id ma si usa per indicare delle variabili di input ed output!!!! (in questo caso si fa' riferimento ad un output!! random-number)
      - id: foo
        uses: giuseppegargani/first_custom_action@0.0.9
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
